# 选择 Mac 开发环境，开启应用的 DEBUG 日志
# gradle bootRun --args='--spring.profiles.active=mac'

app.dir.base: /usr/local/temp/xtuer
logging.level.com.xtuer: debug
logging.level.com.xtuer.mapper: off
spring.thymeleaf.cache : false
