# 1. 配置分组
jdbc:
    driverClassName:        com.mysql.jdbc.Driver    a     # 2. 前后空格会被自动去掉，注释不会被读取
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 密码 # 3. 支持中文
urls:
    - http://127.0.0.1 # 4. 定义数组
    - http://localhost
