spring.server.port: 8080

###############################################################################
#                                    Database                                 #
###############################################################################
# DataSource
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.url     : jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

# Connection Pool: Hikari
spring.datasource.hikari.minimumIdle      : 5
spring.datasource.hikari.maximumPoolSize  : 50
spring.datasource.hikari.idleTimeout      : 30000
spring.datasource.hikari.maxLifetime      : 2000000
spring.datasource.hikari.connectionTimeout: 30000

# MyBatis
mybatis.mapper-locations    : classpath:mapper/**/*.xml
mybatis.type-aliases-package: com.xtuer.bean
mybatis.configuration.map-underscore-to-camel-case: true

###############################################################################
#                                    Quartz                                   #
###############################################################################
spring.quartz.job-store-type: jdbc          # 使用 JDBC 访问数据库持久化 Quartz 数据
spring.quartz.jdbc.initialize-schema: never # 不初始化表结构，手动创建数据库表

# 默认主机名和时间戳生成实例 ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应 qrtz_scheduler_state INSTANCE_NAME 字段
spring.quartz.properties.org.quartz.scheduler.instanceId: AUTO

spring.quartz.properties.org.quartz.jobStore.class                 : org.quartz.impl.jdbcjobstore.JobStoreTX      # 数据库独立事务配置
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass   : org.quartz.impl.jdbcjobstore.StdJDBCDelegate # 数据库驱动代理代理
spring.quartz.properties.org.quartz.jobStore.useProperties         : false
spring.quartz.properties.org.quartz.jobStore.tablePrefix           : qrtz_    # 数据库表前缀
spring.quartz.properties.org.quartz.jobStore.misfireThreshold      : 60000    # 在被认为“失火”之前，调度程序将“容忍”一个 Triggers 将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为 60000（60秒）。
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval: 5000     # 设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
spring.quartz.properties.org.quartz.jobStore.isClustered           : true     # 打开群集功能
spring.quartz.properties.org.quartz.jobStore.dataSource            : quartzDs # 数据源名字，下面的 spring.quartz.properties.org.quartz.dataSource.quartz

# Quartz 使用自己独立的数据源，与上面应用的数据源互不影响
spring.quartz.properties.org.quartz.dataSource.quartzDs.provider: hikaricp
spring.quartz.properties.org.quartz.dataSource.quartzDs.driver  : com.mysql.jdbc.Driver
spring.quartz.properties.org.quartz.dataSource.quartzDs.URL     : jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring.quartz.properties.org.quartz.dataSource.quartzDs.user    : root
spring.quartz.properties.org.quartz.dataSource.quartzDs.password: root
spring.quartz.properties.org.quartz.dataSource.quartzDs.maxConnections: 10

spring.quartz.properties.org.quartz.threadPool.class         : org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount   : 10
spring.quartz.properties.org.quartz.threadPool.threadPriority: 5
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
