
spring.config.import: database-metadata-configs.yml

###############################################################################
#                                    Database                                 #
###############################################################################
# DataSource
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.url     : jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

# Connection Pool: Hikari
spring.datasource.hikari.minimumIdle      : 5
spring.datasource.hikari.maximumPoolSize  : 50
spring.datasource.hikari.idleTimeout      : 30000
spring.datasource.hikari.maxLifetime      : 2000000
spring.datasource.hikari.connectionTimeout: 30000

# MyBatis
mybatis.mapper-locations    : classpath:mapper/**/*.xml
mybatis.type-aliases-package: com.xtuer.bean
mybatis.configuration.map-underscore-to-camel-case: true
