# 获取数据库元数据的配置，每个数据库对应自己的配置。
# SQL 语句中的占位符可为 catalog, schema, table, view, procedure, function 等。
databaseMetadataConfigs:
- type: MYSQL
  label: MySQL
  useCatalog: true
  useSchema: false
  catalogNames.sql: show databases # jdbc
  schemaNames.sql: jdbc
  tableNames.sql: jdbc
  tableNames.tableTypes: [TABLE, SYSTEM TABLE]
  viewNames.sql: jdbc
  viewNames.tableTypes: [VIEW, SYSTEM VIEW]
  procedureNames.sql: jdbc
  functionNames.sql: jdbc
  tableColumn.sql: jdbc
  tableDdl:
    sql: SHOW CREATE TABLE `${catalog}`.`${table}`
    index: 2
  viewDdl:
    sql: SHOW CREATE TABLE `${catalog}`.`${view}`
    index: 2
  procedureDdl:
    sql: |
      SELECT ROUTINE_DEFINITION
      FROM information_schema.ROUTINES
      WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_SCHEMA = '${catalog}' AND ROUTINE_NAME = '${procedure}'
    index: 1
  functionDdl:
    sql: |
      SELECT ROUTINE_DEFINITION
      FROM information_schema.ROUTINES
      WHERE ROUTINE_TYPE = 'FUNCTION' AND ROUTINE_SCHEMA = '${catalog}' AND ROUTINE_NAME = '${function}'
    index: 1

