# 获取数据库元数据的配置，每个数据库对应自己的配置。
databaseMetaDataConfigs:
- type: MYSQL
  label: MySQL
  useCatalog: true
  useSchema: false
  catalogQuery: jdbc
  schemaQuery: jdbc
  tableQuery: jdbc
  tableJdbcTypes: [TABLE, SYSTEM TABLE]
  viewQuery: jdbc
  viewJdbcTypes: [VIEW, SYSTEM VIEW]
  tableColumnQuery: jdbc
  procedureQuery: jdbc
  functionQuery: jdbc
  tableCreateSql: select
  procedureCreateSql: select
  functionCreateSql: select
- type: ORACLE
  label: Oracle
  useCatalog: false
  useSchema: true
  catalogQuery: jdbc
  schemaQuery: jdbc
  tableQuery: jdbc
  tableJdbcTypes: [SYSTEM TABLE]
  viewQuery: jdbc
  viewJdbcTypes: [SYSTEM VIEW, USER VIEW]
  tableColumnQuery: jdbc
  procedureQuery: jdbc
  functionQuery: jdbc
  tableCreateSql: select
  procedureCreateSql: select
  functionCreateSql: select
- type: POSTGRES
  label: PostgreSQL
  useCatalog: true
  useSchema: true
  catalogQuery: jdbc
  schemaQuery: jdbc
  tableQuery: jdbc
  tableJdbcTypes: [SYSTEM TABLE]
  viewQuery: jdbc
  viewJdbcTypes: [SYSTEM VIEW, USER VIEW]
  tableColumnQuery: jdbc
  procedureQuery: jdbc
  functionQuery: jdbc
  tableCreateSql: select
  procedureCreateSql: select
  functionCreateSql: select
